version: "3.3"
services:
  toro_notify_bot:
    build: .
    restart: unless-stopped
    image: toro_notify_bot
    container_name: ToroNotifyBot
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./:/usr/app
    ports:
      - 5010:5010
